import {Images} from '@assets';

export const DATA_BREAKFAST = [
  {
    id: 1,
    img: Images.img_coffee,
    name: 'Cappuccino',
    restaurant: 'Suhani Restaurant',
    price: 20000,
    offer: 10,
    freeDelivery: false,
    discount: null,
  },
  {
    id: 2,
    img: Images.img_rice_egg,
    name: 'Egg and cheese sandwich',
    restaurant: "Mehfil's Place",
    price: 20000,
    freeDelivery: false,
    discount: null,
  },
  {
    id: 3,
    img: Images.img_coffee,
    name: 'Cappuccino',
    restaurant: 'Suhani Restaurant',
    price: 20000,
    freeDelivery: false,
    discount: 10,
  },
  {
    id: 4,
    img: Images.img_rice_egg,
    name: 'Egg and cheese sandwich',
    restaurant: "Mehfil's Place",
    price: 20000,
    freeDelivery: false,
    discount: null,
  },
  {
    id: 5,
    img: Images.img_coffee,
    name: 'Cappuccino',
    restaurant: 'Suhani Restaurant',
    price: 30000,
    freeDelivery: false,
    discount: 5,
  },
];

export const DATA_LUNCH = [
  {
    id: 1,
    img: Images.img_coffee,
    name: 'Cappuccino',
    restaurant: 'Suhani Restaurant',
    price: 20000,
    offer: 10,
    freeDelivery: false,
    discount: null,
  },
  {
    id: 2,
    img: Images.img_rice_egg,
    name: 'Egg and cheese sandwich',
    restaurant: "Mehfil's Place",
    price: 20000,
    freeDelivery: false,
    discount: null,
  },
  {
    id: 3,
    img: Images.img_coffee,
    name: 'Cappuccino',
    restaurant: 'Suhani Restaurant',
    price: 20000,
    freeDelivery: false,
    discount: 10,
  },
  {
    id: 4,
    img: Images.img_rice_egg,
    name: 'Egg and cheese sandwich',
    restaurant: "Mehfil's Place",
    price: 20000,
    freeDelivery: false,
    discount: null,
  },
  {
    id: 5,
    img: Images.img_coffee,
    name: 'Cappuccino',
    restaurant: 'Suhani Restaurant',
    price: 30000,
    freeDelivery: false,
    discount: 5,
  },
];

export const DATA_AFTERNOON = [
  {
    id: 1,
    img: Images.img_coffee,
    name: 'Cappuccino',
    restaurant: 'Suhani Restaurant',
    price: 20000,
    offer: 10,
    freeDelivery: false,
    discount: null,
  },
  {
    id: 2,
    img: Images.img_rice_egg,
    name: 'Egg and cheese sandwich',
    restaurant: "Mehfil's Place",
    price: 20000,
    freeDelivery: false,
    discount: null,
  },
  {
    id: 3,
    img: Images.img_coffee,
    name: 'Cappuccino',
    restaurant: 'Suhani Restaurant',
    price: 20000,
    freeDelivery: false,
    discount: 10,
  },
  {
    id: 4,
    img: Images.img_rice_egg,
    name: 'Egg and cheese sandwich',
    restaurant: "Mehfil's Place",
    price: 20000,
    freeDelivery: false,
    discount: null,
  },
  {
    id: 5,
    img: Images.img_coffee,
    name: 'Cappuccino',
    restaurant: 'Suhani Restaurant',
    price: 30000,
    freeDelivery: false,
    discount: 5,
  },
];
