import I18n from '../i18n/i18n';
function trans() {
  return {
    HOME: I18n.t('HOME', {defaultValue: ''}),
    OFFERS: I18n.t('OFFERS', {defaultValue: ''}),
    CART: I18n.t('CART', {defaultValue: ''}),
    USER: I18n.t('USER', {defaultValue: ''}),
    save_food_new: I18n.t('save_food_new', {defaultValue: ''}),
    set_preferences: I18n.t('set_preferences', {defaultValue: ''}),
    fast_rescued: I18n.t('fast_rescued', {defaultValue: ''}),
    get_started: I18n.t('get_started', {defaultValue: ''}),
    skip: I18n.t('skip', {defaultValue: ''}),
    login: I18n.t('login', {defaultValue: ''}),
    sign_up: I18n.t('sign_up', {defaultValue: ''}),
    forgot_password: I18n.t('forgot_password', {defaultValue: ''}),
    or: I18n.t('or', {defaultValue: ''}),
    login_facebook: I18n.t('login_facebook', {defaultValue: ''}),
    login_google: I18n.t('login_google', {defaultValue: ''}),
    register: I18n.t('register', {defaultValue: ''}),
    full_name: I18n.t('full_name', {defaultValue: ''}),
    phone_number: I18n.t('phone_number', {defaultValue: ''}),
    password: I18n.t('password', {defaultValue: ''}),
    confirm_password: I18n.t('confirm_password', {defaultValue: ''}),

    //home
    home: I18n.t('home', {defaultValue: ''}),
    search_food: I18n.t('search_food', {defaultValue: ''}),
    hot_deal: I18n.t('hot_deal', {defaultValue: ''}),
    new_on_fastfood: I18n.t('new_on_fastfood', {defaultValue: ''}),
    save_food: I18n.t('save_food', {defaultValue: ''}),
    set_preference: I18n.t('set_preference', {defaultValue: ''}),
    looking_for: I18n.t('looking_for', {defaultValue: ''}),
    breakfast: I18n.t('breakfast', {defaultValue: ''}),
    like_to_taste: I18n.t('like_to_taste', {defaultValue: ''}),
    order_again: I18n.t('order_again', {defaultValue: ''}),
    your_ordered: I18n.t('your_ordered', {defaultValue: ''}),

    all: I18n.t('all', {defaultValue: ''}),
    all_restaurant: I18n.t('all_restaurant', {defaultValue: ''}),
    restaurant_near_you: I18n.t('restaurant_near_you', {defaultValue: ''}),
    free_delivery: I18n.t('free_delivery', {defaultValue: ''}),
    recent_search: I18n.t('recent_search', {defaultValue: ''}),
    description: I18n.t('description', {defaultValue: ''}),
    nutritional_value: I18n.t('nutritional_value', {defaultValue: ''}),
    ingredients: I18n.t('ingredients', {defaultValue: ''}),

    //offer
    big_offers: I18n.t('big_offers', {defaultValue: ''}),
    a_big_binge: I18n.t('a_big_binge', {defaultValue: ''}),
    exclusively: I18n.t('exclusively', {defaultValue: ''}),
    deal_icious: I18n.t('deal_icious', {defaultValue: ''}),
    best_offers: I18n.t('best_offers', {defaultValue: ''}),
    just_for_you: I18n.t('just_for_you', {defaultValue: ''}),
    //Cart
    cart: I18n.t('cart', {defaultValue: ''}),
    edit_address: I18n.t('edit_address', {defaultValue: ''}),
    delete_food: I18n.t('delete_food', {defaultValue: ''}),
    cancel: I18n.t('cancel', {defaultValue: ''}),
    confirm: I18n.t('confirm', {defaultValue: ''}),
    voucher: I18n.t('voucher', {defaultValue: ''}),
    total_food: I18n.t('total_food', {defaultValue: ''}),
    delivery: I18n.t('delivery', {defaultValue: ''}),
    total: I18n.t('total', {defaultValue: ''}),
    //Profile
    personal_detail: I18n.t('personal_detail', {defaultValue: ''}),
    edit: I18n.t('edit', {defaultValue: ''}),
    bookmark: I18n.t('bookmark', {defaultValue: ''}),
    notification: I18n.t('notification', {defaultValue: ''}),
    setting: I18n.t('setting', {defaultValue: ''}),
    payment: I18n.t('payment', {defaultValue: ''}),
    your_orders: I18n.t('your_orders', {defaultValue: ''}),
    history_order: I18n.t('history_order', {defaultValue: ''}),
    my_preference: I18n.t('my_preference', {defaultValue: ''}),
    help: I18n.t('help', {defaultValue: ''}),
    send_feedback: I18n.t('send_feedback', {defaultValue: ''}),
    report: I18n.t('report', {defaultValue: ''}),
    rate: I18n.t('rate', {defaultValue: ''}),
    logout: I18n.t('logout', {defaultValue: ''}),
    about: I18n.t('about', {defaultValue: ''}),
    update: I18n.t('update', {defaultValue: ''}),
    language: I18n.t('language', {defaultValue: ''}),
  };
}
export default trans;
